### ISSUE TITLE
Stack Buffer Overflow in Script Interpreter

### ISSUE THREAD

**Issue by federico22598** [citizenfx/fivem#1034]
[![PoC Demonstration Video](http://img.youtube.com/vi/52-s2CNjaZw/0.jpg)](http://www.youtube.com/watch?v=52-s2CNjaZw "PoC Demonstration Video")
_<sub>PoC demonstration video</sub>_

A bug in the function `__Lua_InvokeNative` —delegate to the Citizen API functions `InvokeNative` and `InvokeNative2`— grants Lua scripts full control of the stack and enables gameservers to execute arbitrary code in the machine of the player. Every Lua argument following the native identifier is translated to a C value and then naively written to an auxiliary structure that lies on the stack of the function, which, as all others involved, never cares enough to know whether there is space available or not. In doing this, it is aided greatly by `Lua_PushContextArgument`: 

https://github.com/citizenfx/fivem/blob/2405f994806af11f8e9160f9ea66a8eed6461667/code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp#L570-L577

... which is, for the matter in question, equivalent to `fxLuaNativeContext_PushArgument`:

https://github.com/citizenfx/fivem/blob/2405f994806af11f8e9160f9ea66a8eed6461667/code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp#L337-L424

... which is, for all that matters, equivalent to a blind shrimp:

https://github.com/citizenfx/fivem/blob/2405f994806af11f8e9160f9ea66a8eed6461667/code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp#L48-L77

The particular use of `__declspec(safebuffers)` in all of these functions further eases exploitation. 

Moreover, the bug seems also to be present in the JavaScript interpreter:

https://github.com/citizenfx/fivem/blob/2405f994806af11f8e9160f9ea66a8eed6461667/code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp#L1105-L1134

**Comment by blattersturm** [comment]
Yeah, I'm not sure why there's no actual baseline sanity checking (or slack space to make sanity checking more trivial i.e. not need a branch on every iteration) here.

There's a lot easier code execution compared to this anyway in native invocation (type confusion for pointer arguments, infinite write-what-where primitives, aided by the fact that the game executable can't be W^X due to DRM), so this is a much more roundabout way to break things than _just using any memory-writing calls_.

Intent exists to sandbox the game process into a low-trust appcontainer, but the non-trivial case of handling GPU driver calls is making it such that this hasn't been done yet.

**Comment by blattersturm** [comment]
For the time being I'll just drop the safebuffers so this'll be hit by a GS fastfail, least likely to break anything else that way at least I guess.

**Comment by blattersturm** [comment]
Performance-wise it might make more sense to account for the maximum amount of arguments pushed by a single argument, have extra space in the arguments buffer to account for this, and do a single check based on the arity of the actual call.
