### ISSUE TITLE
Bold emoji char replaces next chars

### ISSUE THREAD

**Issue by rdelian** [citizenfx/fivem#1112]
Hello, I've come across an _issue_ 

If there is an emoji between `~h~` and the emoji is next to `~h~` without any spaces all chars after last `~h~` will be replaced with the emoji

_For example_
```lua
"~h~Abc🍕~h~pizza" --> "Abc🍕🍕🍕🍕🍕🍕"
```
If there is a space between the emoji and the last `~h~` it works as expected

---------

**Repro code**
```lua
Citizen.CreateThread(function()
	-- It doesn't matter how text is displayed, 
	-- tested with BeginTextCommandDisplayHelp, BeginTextCommandPrint

	local function TheFeedPost(text)
		BeginTextCommandThefeedPost('STRING')
		AddTextComponentSubstringPlayerName(text)
		EndTextCommandThefeedPostTicker(true, false)
	end

	local cases = {
		"~h~🍕~h~pizza", "~h~ 🍕~h~pizza",
		"<b>ABC🍕</b>pizza", "<b>ABC 🍕</b>pizza",
	}

	local run_id = GetGameTimer() .. ' '

	for i = 1, #cases do
		TheFeedPost(run_id .. cases[i])
	end
end)
```

**Client**: Release

**Comment by blattersturm** [comment]
That's an odd one - it seems something is acting up with rendering of the replaced img tag: the formatted text is still fine:

```xml
111721 <b><img src='flex_img_1f355' width='15' height='15'/></b>pizza
```

**Comment by blattersturm** [comment]
Might be `glyphIt` in `GFxTextLineBuffer::Display` remains.. stuck?

**Comment by blattersturm** [comment]
Nope, it seems by this point the list of GlyphEntry is already a _lot_ of pizza.

**Comment by blattersturm** [comment]
It seems that an \<img\> right before a closing format tag will result in all glyphs being the same img format repeated instead of a proper end-formatting glyph. Odd.

**Comment by blattersturm** [comment]
Ah.

After encountering a \<IMG> tag, GFx will mark the _current format_ at the nested index, as well as the _last format_ as not having an image desc, while also setting PresentMask_ImageDesc on this format to indicate this has to be cleared when rendering.

However, when the \<IMG> is the last entry in a nested element (i.e. the \<B>), it will tell the B format to reset the image desc, but the B format gets cleared next iteration by the \</B> tag, so the ImageDesc remains set during presentation since the parent (default, in this case) text format doesn't tell it to clear such.

This seems to be an actual bug in GFx, and should be fixable (albeit hackily) by looping over the element stack and setting parents to _also_ clear ImageDesc, or maybe a bit more cleanly by having a pop (closing element) inherit the PresentMask from the current element's text format.

**Comment by blattersturm** [comment]
![image](https://user-images.githubusercontent.com/24576130/140081641-3b4a6e52-e2a8-4312-8473-beed22243066.png)

:)

**Comment by rdelian** [comment]
You rock!
