### ISSUE TITLE
A few questions on the following topics [Testing][CLI tooling][New contributor advice]

### ISSUE THREAD

**Issue by shionhart** [citizenfx/fivem#1281]
Hello everyone,

I have a few questions.

1. Outside of manual testing the functionality of a resource, is there a common pattern for building and running component/functional tests while using some sort of fivem runtime environment or fivem runtime mocks? If so, would you please explain how it is usually done? If not, is there any idea amongst the project's current developers on how something like that would be added? I am willing to help build it. I lack understanding of this codebase to be able to design it though.

2. Are there programmatic hooks or a command line tool to be able to execute server/client commands? I ask because I develop using typescript and I'd like to be able to do something like:`npm run build && cfx --refresh && cfx --restart <resourceName>`.

3. While the README files are help in locating pieces of this codebase, there isn't a lot to go on as far as the overall design of FiveM. Do any developers of this repo offer paid/free courses/lessons on how to go about understanding this? I'm sure I could figure it out after many months of reading through the source, it is much easier to get a hi-level understanding from an existing dev, at least that is what I've found from the software companies I've worked at.

4. Alternative to being taught directly, are there issues that would be good for newbies to the repo? Then, I can learn through the roasting of my PR. Haha.

Thanks for your time,
Steel

**Comment by blattersturm** [comment]
First off, the 'Issues' section here is for _actionable tasks_ only, any discussion generally should be done on the [forums](https://forum.cfx.re/). I'll close this issue (but not lock it) since it is not an actionable to-do.

As to your questions:

1. No, and no. 'fivem runtime mocks' would be near-impossible either since _especially_ on the client the project is just a low-level binding to game code, and on the server it's mostly a router for game code/data structures. Since 'game code' is very much out of our control, this can't have support for automated tests added trivially.
2. The server implements a Quake 3-style rcon protocol over the UDP port, where the client implements Valve's VConsole2 protocol over port 29100 or so.
3. Not.. really. Without knowing what you're trying to do, it's difficult to provide any starting point. Generally, client runtime is very much intertwined with the game code lifecycle, and the server codebase is mostly a bunch of parallel libuv loops exchanging messages in.. some way.
4. Hard to tell at this point. There's a variety of disciplines involved here and a lot of it depends on actually reading listings of disassembled game code and going from there.

**Comment by shionhart** [comment]
Thank you @blattersturm.
Your answers have given me enough information for now.
I'll direct future questions to the forum.
