### ISSUE TITLE
Fivem story mode doesn't work properly because of this line code

### ISSUE THREAD

**Issue by bigman183** [citizenfx/fivem#1321]
https://github.com/citizenfx/fivem/blob/599fe9142abb90b2c967fb3a0525f23c3b0013a1/code/components/rage-scripting-five/src/scrEngine.cpp#L533

**Comment by blattersturm** [comment]
... huh? What do you mean by 'does not work properly'?

'This line code' in fact is meant to make it work at all.

**Comment by iAboodx** [comment]
yeah .. story mode does not work for me too

**Comment by blattersturm** [comment]
> yeah .. story mode does not work for me too

... okay? Any more info?

**Comment by blattersturm** [comment]
Ah, found out why this issue is even existent or why people are referring to 'this line code', probably they got a crash dialog and decided this was the best way to ask.

What surprises me, however, is that nobody found it was broken on canary for _weeks_, if it's even broken at all (can't check, not near any Windows PC).
