### ISSUE TITLE
weaponDamageEvent  

### ISSUE THREAD

**Issue by POLYFAY** [citizenfx/fivem#1426]
Invalid weaponType returned.

use weapon  Bottle
"weaponType": 4192643659,

Windows server build  5531
{
   "damageType":2,
   "actionResultName":1185336465,
   "f112_1":0,
   "damageTime":0,
   "weaponType":4192643659,
   "hasVehicleData":false,
   "overrideDefaultDamage":true,
   "localPosX":0.0,
   "actionResultId":32788,
   "impactDirX":0.0,
   "impactDirY":0.0,
   "willKill":false,
   "f112":false,
   "impactDirZ":0.0,
   "tyreIndex":0,
   "weaponDamage":1,
   "f133":false,
   "isNetTargetPos":false,
   "localPosY":0.0,
   "parentGlobalId":1,
   "f104":2289004634,
   "hitGlobalIds":[
      14
   ],
   "suspensionIndex":0,
   "hitGlobalId":14,
   "hasImpactDir":false,
   "f120":0,
   "hasActionResult":true,
   "hitWeaponAmmoAttachment":false,
   "damageFlags":778,
   "localPosZ":0.0,
   "hitComponent":0,
   "silenced":false,
   "hitEntityWeapon":false
}

**Comment by Disquse** [comment]
> use weapon Bottle
> "weaponType": 4192643659,

Weapon name hash of `weapon_bottle` is `0xf9e6aa4b`, which is `4192643659` in dec, what's wrong?

**Comment by K3YOMI** [comment]
I've actually came across something like this. Some weapon dec hashes return different from the actual weapon being used. I've only seen *one* weapon do this.

**Comment by Korioz** [comment]
You are probably talking about sign extension issue, you don't have to worry about it but if you need the same hash for some reason just force it into an unsigned int by doing `HASH & 0xFFFFFFFF`.

To quote gottfriedleibniz :
*-761663767 and 3533303529 are the same bits/bytes when stored in a 4 byte integer. In Lua integers are longs by default.
(-761663767) & 0xFFFFFFFF == 3533303529
Usually won't be an issue because GTA & most of FiveM will do the casting internally*

**Comment by gottfriedleibniz** [comment]
I would reference https://github.com/citizenfx/fivem/issues/1427#issuecomment-1109579689 as that explanation is more precise. What I said was a lazy oversimplification.

There is still some lingering inconsistencies in the current state data parser(s) (e.g., grep `Read<int>(32)` and `Read<uint32_t>(32)`) and this issue could probably use some documentation somewhere to clarify things.
