### ISSUE TITLE
Unable to have more than 24 players.

### ISSUE THREAD

**Issue by clarjon1** [citizenfx/fivem#16]
At the time of writing, the released version of FiveM only supports up to 24 players in an instance. This is a hard coded limit, and I've been told that people who modify the source to allow more than 24 players are removed from the server listings.

As a game server admin, I find it highly frustrating when a game or service has a hard coded limit such as this. It prevents me from being able to expand my communities by purchasing more powerful hardware in order to allow the game or service to be run. It also raises management issues, by preventing staff from being able to use the server due to the low limits of users. It also encourages stagnation of these communities, as people who want to play can be locked out of the servers for hours. For those who make a living from Twitch Streaming, fivem is appearing to fast become a unappealing thing to stream, as these limits can mean that, with how commonly fivem crashes, their entire plan for the evening stream is screwed up -- nobody wants to watch someone stream a server list for an hour as they try to get back into the RP community again.  I have seen streamers lose large numbers of viewers due to this exact issue.

There are some communities that are getting around this by setting up multiple instances of the fivem software. However, this is a waste of resources, and makes community management much more difficult, as more staff is needed for each server created to watch each server, instead of allowing a small dedicated team watch a large number of users on a single server.

Game administrators should be able to test and set the user limits themselves. Whether a server can support 10, 24, or even 100 players should be up to the testing of the administration team and the resources they have provided to the service. Look at other games, such as Minecraft, which vary between as few as 5 on a server to hundreds of players at once, with the limit set by the administrator with such things as the community size and server resources in mind.

**Comment by kanersps** [comment]
This has nothing to do with a hard-coded limit. One sync will make more players possible but this limit isn't intentionally put in.

**Comment by kanersps** [comment]
@kanersps Work now?

**Comment by Kngrektor** [comment]
Hi! I just wanted to point out some misinformed statements and what not.

>up to 24 players in an instance.

iirc this has to do with the **default** max player count of a GTA:O session and is pretty easy to bump up to 32. Anything above 32 won't work as the game isn't built for it. This is what OneSync adresses.

> This is a hard coded limit

The actual limit can easily be changed in the hardcap resource. And plenty of server owners have tried this and caused the "Failed to connect to session provider" error. There was a peak of servers doing this, and therefore also a peak of people asking for support. My guess is that this is why you'll get blacklisted.

There's also other issues that server owners & scripters cause. I would guess 90% of session splits, instancing or whatever you want to call it is caused by non-async MySQL queries.

> with how commonly fivem crashes

I believe the most common crashes (https://crashes.fivem.net/stats/version/1.0.0.0) are fixed pretty quickly, especially if it's reproducible.
I've never seen a streamer try get any support, or even show the CrashID which makes it a lot harder.


>purchasing more powerful hardware in order to allow the game or service to be run.

This should not be needed as the server is basically a realy. It doesn't do many calculations, however it does usage a ton of bandwidth. You can run a (or maybe even more) server(s) on a Raspberry pi. I've personally ran 5+ servers on a $3.5/month OVH server (VPS SSD 1) with no problem.

Sorry for the probably shit response but I'm tired and normally don't write "long" answers. Also I woulnd't be suprised if someone corrected me on some thing.

**Comment by blattersturm** [comment]
>At the time of writing, the released version of FiveM only supports up to 24 players in an instance. This is a hard coded limit, and I've been told that people who modify the source to allow more than 24 players are removed from the server listings.

Modifying the source won't 'allow more than 24 players', these players will not be able to join and will end up receiving a 'Could not connect to session provider' error - this is why these servers get blacklisted: people do not understand that currently FiveM hasn't extended the game code to a sufficient extent yet to allow higher player counts - or that FiveM even relies on game code at all.

Reverse engineering is different from developing software from scratch, the actual player limit is _nowhere_ in the FiveM source code: `hardcap` only exists so that servers don't accidentally break the limit and players don't get frustrated trying to join a server that will just error out and force them to restart the game!

>As a game server admin, I find it highly frustrating when a game or service has a hard coded limit such as this. It prevents me from being able to expand my communities by purchasing more powerful hardware in order to allow the game or service to be run.

As a game modification developer, I find it highly frustrating when users don't bother taking what we say for granted. It lowers team morale and prevents us from performing important development, such as rewriting the network frameworks as mentioned on https://fivem.net/#24-slots as we have to deal with replies to comments like these.

>It also raises management issues, by preventing staff from being able to use the server due to the low limits of users.

Does 'staff' have to 'manage' a server, specifically? Also, a smart server developer could lower the `hardcap` limit to 23 slots and always reserve one slot for staff. It isn't that hard.

>It also encourages stagnation of these communities, as people who want to play can be locked out of the servers for hours.

Autoscaling server instances could be a workaround for this. Do note FiveM was never meant to be used for this 'popular' a scenario, at least not until the OneSync framework is completed - you're kind of using the modification for something it is not nearly ready for.

>For those who make a living from Twitch Streaming, fivem is appearing to fast become a unappealing thing to stream

Do we care about 'streamers' and people making money from it? FiveM isn't a vehicle for people to make money from, if they find something more financially appealing, then so be it.

>as these limits can mean that, with how commonly fivem crashes

Does it? Most crashes are caused by servers running bad/broken modifications (or rejoining the game after being kicked/disconnected after playing for a while), and given how most popular servers that cause these issues don't even _have any means for us to contact management_ and nobody bothers posting about their issue and _working with us to solve these issues_, they're not resolved so far.

Have you had the game crash? Probably so. Did you post your crash ID on the forums, including a series of steps that you used to cause the problem and that could help us reproduce and fix the issue? Doubtful.

We don't play the game remotely as much as these 'streamers', and most often the servers causing issues are both either whitelisted or full, allowing our development team no access to these servers - and most of the time server management isn't able to be contacted either.

>their entire plan for the evening stream is screwed up -- nobody wants to watch someone stream a server list for an hour as they try to get back into the RP community again. I have seen streamers lose large numbers of viewers due to this exact issue.

Again, financial appeal of FiveM to others is not our concern, as you might know, making money from FiveM is expressly prohibited by the FiveM Service Agreement.

>There are some communities that are getting around this by setting up multiple instances of the fivem software. However, this is a waste of resources, and makes community management much more difficult, as more staff is needed for each server created to watch each server, instead of allowing a small dedicated team watch a large number of users on a single server.

And until there's more slots (which ISN'T DONE BY EDITING A SINGLE LUA FILE) that's the only way to handle things at this point.

Also - why do servers need dedicated people watching them: with some smart coding an in-game incident reporting system can be developed which combined with having a reserved slot would allow staff to manage servers or whatever they do anyway.

>Game administrators should be able to test and set the user limits themselves.

This would be the case if FiveM were _its own game and not a modification to an existing game_.

>Whether a server can support 10, 24, or even 100 players should be up to the testing of the administration team and the resources they have provided to the service.

And it will be, once the modification **actually supports this high a slot count** - currently _it doesn't_, and no fiddling that a 'server administrator' can do will resolve this.

Do you think we're limiting this value just to spite server administrators, players and 'Twitch streamers', and not due to _actual technical limitations_?

>Look at other games, such as Minecraft

which isn't a modification to an existing game but is a scratch-developed game by a multi-billion-dollar corporation which employs over 100K people, not a modification to a commercial game developed by 5 people in their spare time that don't get paid for it and have to deal with crap like this in-between actually working on the modification code

>which vary between as few as 5 on a server to hundreds of players at once, with the limit set by the administrator with such things as the community size and server resources in mind.

which will be the exact case once the OneSync framework is implemented.

**Comment by clarjon1** [comment]
I'm glad to hear about the oneSync Framework. I apologize, I was unaware that it was due to a bug in the existing unmodded game code that you were redirecting. The info I had dug up via google searches did not make that clear.

And, as someone who has worked along side Mojang as part of their volunteer support team for many years, I can assure you that Minecraft definitely was not developed from scratch by a multi billion dollar corporation. It's time for a quick history lesson!

It's a tech demo written by a single person that kept adding features because of how popular it had gotten. As time went on, this single developer started making enough money from it to get a small team to help. He made a company out of it. I think it was about 10 devs working on the project when Microsoft bought it out, really really late in the game's development. As I recall, There's now a total of 13 devs, according to their employee page.( Also, lol, they have 10 "brand enforcement" employees) 

Even still, this multimillion dollar game has no official support chat -- just a bunch of fans of the game sitting in an IRC channel.

 The code is in desperate need of a rewrite -- it has been for YEARS. There has not been a full rewrite of the game code, so it still has the tech demo structure at its core. The netcode is awful, but it works. It's very easy to create hacked clients and wreak havoc on servers, so barely anyone ever has a "vanilla" server unless it's very closely whitelisted. Nearly every minecraft server is run using fan made, modded servers -- except for the ones in the console environment -- and the console versions aren't even written by Mojang, it's contracted out to another publisher, "4J Studios".
