### ISSUE TITLE
AddReplaceTexture does not support 'delayed' DUI handle textures

### ISSUE THREAD

**Issue by VanishedMC** [citizenfx/fivem#1684]
The `AddReplaceTexture` Native works perfectly fine on Release, but does not work at all on the beta or latest branches.
In the native's documentation it is listed as experimental, though it would be great if it is fixed before the next Release update

**Comment by blattersturm** [comment]
Do you have any actual resource that doesn't work, that we can test on a clean server? Mainly so we don't waste time trying to reproduce an issue that only happens with some specific parameters, textures, or other environment constraints.

**Comment by VanishedMC** [comment]
```lua
plates = {
	{ "plate01", "https://i.imgur.com/bpOLgrj.png", 540, 300 },
	{ "plate01_n", "https://i.imgur.com/bpOLgrj.png", 540, 300 },
	{ "yankton_plate", "https://i.imgur.com/Am5Pg6u.png", 540, 300 },
	{ "yankton_plate_n", "https://i.imgur.com/Am5Pg6u.png", 540, 300 },
}

local txd = CreateRuntimeTxd("licenseplatetxd")

for _, plate in pairs(plates) do
	local duiObj = CreateDui(plate[2], plate[3], plate[4])
	local dui = GetDuiHandle(duiObj)
	local tx = CreateRuntimeTextureFromDuiHandle(txd, plate[1], dui)

	AddReplaceTexture("vehshare", plate[1], "licenseplatetxd", plate[1])
end
```
This little script works great to replace license plates on Release, but does nothing on Beta or Latest. I have also tried printing the result of `AddReplaceTexture`, which is `true` on release, and `false` on beta

**Comment by MegaMagnum** [comment]
Yes, I am having the same problem on my server! Release works just fine but when a player is on beta it doenst work

**Comment by blattersturm** [comment]
1. Using DUI here for static images is _extremely_ inefficient. You should bundle this in your resource either as a custom .ytd file or use [CreateRuntimeTextureFromImage](https://docs.fivem.net/natives/?_0x786D8BC3) with a file in your resource.
2. This is likely another case of [a similar issue reported on the forums](https://forum.cfx.re/t/regression-duis-not-rendering-on-runtime-textures/4933876), since this also doesn't wait for IsDuiAvailable before using the added texture.

   A fix would be hooking something like the delayed creation from https://github.com/citizenfx/fivem/commit/09e00310ea53ce58166f3e745a83ebdcc23654bd up to AddReplaceTexture as well.

**Comment by blattersturm** [comment]
Due to unforeseen issues leading to stress this will not be looked into any time soon. Sorry.
