### ISSUE TITLE
Resource will be stopped before asynchronous onResourceStop

### ISSUE THREAD

**Issue by birthdates** [citizenfx/fivem#1762]
In a resource I am creating, I require data to be saved on unload, and some other asynchronous things. However, I listen for the unload with `onResourceStop` and the promises never get resolved/called. Is there a way around this or a fix?

Example:
```javascript
on("onResourceStop", async (resourceName: string) => {
    if (resourceName !== GetCurrentResourceName()) return;
    await someAsyncStuff();
    console.log("Done!"); // Never happens
});
```

OR:
```javascript
on("onResourceStop", (resourceName: string) => {
    if (resourceName !== GetCurrentResourceName()) return;
    someAsyncStuff().then(() => {
        console.log("Done!"); // Never happens
    });
});
```

Also, please note that I cannot do this data saving synchronously with the library I am using.

**Comment by birthdates** [comment]
A possible workaround would be making a command to unload first, then restart the script but this isn't possible because of [this issue](https://github.com/citizenfx/fivem/issues/14210)

**Comment by blattersturm** [comment]
I don't think there's any particular way this can safely be implemented. Asynchronous event handlers aren't a thing the host handles here and quite a lot of logic expects resources to be able to start and stop synchronously (there was a patch set for 'async resources' but it would have led to a large amount of compatibility issues with resources starting/stopping out of the 'expected' order as users don't correctly indicate dependencies), and similarly so stopping the currently executing resource is also unlikely to ever work as stopping a resource will unload the scripting runtime that the StopResource call will return into.

It would be easier to just periodically save non-critical data and save critical data as soon as possible rather than try to account only for clean stops/exits.

**Comment by birthdates** [comment]
I understand that it would be easier to periodically save data, and I do. However, I'm working on my script constantly in a dev environment and I restart the script a lot. I have made a little workaround with a separate resource:

```javascript
RegisterCommand(
    "ref",
    async () => {
        await unloadOtherResource(); // Using exports
        setImmediate(() => { // Required or StopResource will pause this script?
            StopResource("resource");
            StartResource("resource");
        });
    },
    true
);
```
