### ISSUE TITLE
Importing utf-8-validate using node api leads to instant server crash.

### ISSUE THREAD

**Issue by maicek** [citizenfx/fivem#1781]
Hello, I recently made server artifacts update on my local development server and the problem happend when server boots up and want to run resource that imports 'socket.io-client' on server side. 

I have done some research and i discovered very quickly that problem occurs when imported module is just utf-8-validate (i opened dmp file in windbg and i saw that node_api was an problem, and if i got little bit depper i found problematic module).

![image](https://user-images.githubusercontent.com/46402692/210645214-a0c41ef3-9841-4b05-baad-5587ffbb90d3.png)

Problematic artifacts: 6189
Working artifacts: 6182

I will do some research soon about last working version and provide more info.

**Comment by maicek** [comment]
Update: latest version that works is 6182

**Comment by blattersturm** [comment]
I don't believe binary Node.js modules ever even should have worked. Can you provide a more accessible repro, and an actual dump file?

**Comment by maicek** [comment]
Is it safe to drop here full dump?

**Comment by maicek** [comment]
Here is dump from my minimal reproduction server and actual files https://dropmefiles.com/mRj8t

I gave you simple readme steps to get this problem.

I also noticed that problem occurs when socket.io-client is combined in dependencies with @vue/devtools which is so weird.

**Comment by blattersturm** [comment]
> We have running at least 4 machines running same repository and we didn't notice for long time any problems with binary node modules.

If the only binary module you've attempted to use is `utf-8-validate`, this is correct, since it has a [fallback JS implementation](https://github.com/websockets/utf-8-validate/blob/569049a5f1f438296ef35048e9b8efab30485f54/fallback.js) that gets used if [the binary fails to load](https://github.com/websockets/utf-8-validate/blob/569049a5f1f438296ef35048e9b8efab30485f54/index.js#L6).

In this case, the _regression_ likely is that instead of the binary module failing to load, it trips a crash in one of the API hooks thereabouts.
