### ISSUE TITLE
Canary crash - adhensive.dll

### ISSUE THREAD

**Issue by Tudounaozier** [citizenfx/fivem#1787]
Hello,

I have about ~10 to ~15 players reporting FiveM crashes upon start. Please see the attached screenshot. All of them have the exact same crash.

https://i.imgur.com/PkSBCdv.png

Thank you,

Tudounaozi

**Comment by AdrianIsBored** [comment]
Seems to always crash when the SavedBuildNumber is 2802 on canary. Here is a [full dump](https://drive.google.com/file/d/11pu03pJjrZjQTPmWbRXI2xeG9J9gKI28/view?usp=share_link) if this helps. The crashes seem to be always caused by either an illegal memory instruction or an invalid memory address (0x00000000).
