### ISSUE TITLE
NetworkGetEntityFromNetworkId sends out warnings to production/dev mode, when accessing a non existing entity

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#1803]
The function returns 0 on fail, so why is it warning/erroring in the console?

For example, I am using CreateVehicle with OneSync to spawn vehicles on the server and then using statebags to network some things to the client.
The time, the state bag handler reports the state bag (same for TriggerClientEvent), the entity still not exists however, so I am using a while loop to wait for the entity to be created on the client (as there is no entityCreated clientside afaik also).

This error however pops up and will confuse players and make them report the error to me (while not being my fault):
https://i.imgur.com/2E2AcPP.png

It is simply not needed, as the function just returns 0 anyway, if it doesn't find any entity.
I can't think of any different function to check preemptily, so this error does not appear.

I would propose to remove the warning, as it serves no purpose or add another function which doesn't error on fail.
Optionally adding a client event handler for networked entity spawning would be a good solution too.

The code looks like this:
```
local vehicle = NetworkGetEntityFromNetworkId(netId)
local trys = 0
while vehicle == 0 do
	vehicle = NetworkGetEntityFromNetworkId(netId)
	Wait(100)
	trys = trys + 1
	if trys > 300 then
		break
	end
end
```

**Comment by blattersturm** [comment]
> The function returns 0 on fail, so why is it warning/erroring in the console?

Because it always has, and it is good form to check for existence first.

This is not going to get changed.

**Comment by mcNuggets1** [comment]
Thanks, I've searched for a long time, but because of the bad documentation couldn't find anything.

**Comment by blattersturm** [comment]
'The bad documentation', huh? Searching the natives list for 'networkid' returned these two natives *instantly*, do you have any more concrete suggestions on improving 'the bad documentation' or are you just going to post non-constructive derivative questions?

**Comment by mcNuggets1** [comment]
There is not even a description or link to the native for the native that errors on "incorrect usage".
That's probably the best way to improve that. Also the warning, should be an error then directing to the proper functions to be used.
That most natives don't have any description doesn't shout good documentation for me.

I tried to google for the natives multiple times.
Even big frameworks like ESX do it wrong.
There was just no way imagineable for me.

**Comment by blattersturm** [comment]
> There is not even a description for the native at all

The name itself is already descriptive enough.

> or link to the better to use native for the native that errors on "incorrect usage".

... because nobody ever actually asked for it or told us they ran into this. We aren't somehow magically psychic.

> That most natives don't have any description doesn't shout good documentation for me.

'Most natives' are implemented by Rockstar and not us, so we _don't even know what they do or how to describe them_. This native however is _extremely descriptively named_ and it does really not even need a description at all to be able to find or understand it.

> Also the lack of CEvent documentaiton is harsh.

These are _yet again implemented by Rockstar and we just expose them in a raw way_. If you found anything about them you're welcome to improve the documentation though, just like with the natives.

> I tried to google for the natives multiple times, didn't find nothing but videos.

Google is kind of shit these days, directly searching the natives list is a better bet.

> Even big frameworks like ESX do it wrong.

Most 'big frameworks' seem to do _everything_ wrong as the authors seem to have put no effort into even trying to think if there's a right way to do anything.

Given this discussion is inappropriate for this platform by now, I'll be locking this conversation - you can continue this on the [forums](https://forum.cfx.re/) if you so desire, though most of this seems to rather indicate a lack of understanding how a _game modification platform_ works.
