### ISSUE TITLE
Weird console bug

### ISSUE THREAD

**Issue by Xenius97** [citizenfx/fivem#1827]
Hi,

After adding tee to command line it will become weird.
Using Windows 11 latest build.

Screenshot:
![image](https://user-images.githubusercontent.com/6568348/214157307-81421415-c0b3-4685-902d-362130d92626.png)

Command line:
`.\server\FXServer.exe +exec server.cfg | C:\msys64\usr\bin\tee.exe -a logs/server.log`

**Comment by blattersturm** [comment]
Curious. Would this perhaps be an inaccuracy in Windows Terminal or MSYS2's terminal handling?

**Comment by gottfriedleibniz** [comment]
I am not a Windows console internals expert, so I can only speculate. But based on those screenshots, it *seems* like `FILE_TYPE_PIPE` is not playing nicely with the Windows Console API (`SetConsole...`, `GetConsole...`, etc.) used by replxx (instead of VT100).

Up until Windows released ConPTY, using an adapter like winpty was quite common. The program is still bundled with plenty of software so no install would be required, e.g.,

```bash
`& 'C:\Program Files\Git\usr\bin\winpty.exe' -Xallow-non-tty [...] | C:\msys64\usr\bin\tee.exe -a logs/server.log
```

**Comment by gottfriedleibniz** [comment]
Marking as stale. If still an issue, please reopen.
