### ISSUE TITLE
Resolve unhelpful error stacktrace

### ISSUE THREAD

**Issue by mcNuggets1** [citizenfx/fivem#1908]
[  script:es_extended] Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:157: msgpack format data is incomplete
[  script:es_extended] stack traceback:
[  script:es_extended] 	[C]: in function 'msgpack.unpack'
[  script:es_extended] 	citizen:/scripting/lua/scheduler.lua:157: in function <citizen:/scripting/lua/scheduler.lua:148>

I got this error and I am unsure what it means and how I am supposed the reason behind it.
The error is extremely unhelpful.

**Comment by Keyinator** [comment]
Would be nice if you could put in more effort.

Are there any errors before and after? Also what artifact and os are you running?

**Comment by mcNuggets1** [comment]
Can't know what they want, if there is no template to fill in the information needed.
Also I'm paying a service, would be nice if I pay for something, that I would get some support in return instead of a closing of my issue without any information given about it.

I run on 6247 on linux.
Error appeared out of nowhere, then just randomly stopped.
It spammed for a while.

I just wanted to know the reason for the error in the first place.

**Comment by blattersturm** [comment]
This isn't a place for 'support', you quite literally are in the wrong place for that. Also, we have nothing to do with 'es_extended' and also don't know 'the reason for the error in the first place' since *you* are the one apparently having this 'error', we don't even know how to cause it nor do we have access to your setup where you do seem to cause it, so we can't really provide any more information either.

**Comment by blattersturm** [comment]
A few more points:

- The issue was closed since it's not actionable, to keep this place clean.
- You're not paying for 'guaranteed solutions to vague questions'. You get 'support' fine for the features you pay for, but also not here, but on the *support site*, where people who are paid to help with paid features help with said features.
- 'That should not sound rude' is usually a sign of a lack of reflection on the situation.
- This sort of error message should not even show in the first place. The fact this can even show would likely be a bug *somewhere*, and we're, again, literally as confused as you are about it, and the behavior you're showing doesn't really invite anyone to ask any sort of followup question either.

We don't magically know everything *either* nor are we somehow 'hiding information from you behind vague error messages'. Generally, if you're having a 'vague error', this is because you're *actually* hitting a new edge case, and being the person who has such an error happen to them, you're better equipped to find out what's going on than we are, *not* being able to have such an error even occur at all.

I've locked this discussion since there's a chance this'll turn into yet another back-and-forth argument, draining everyone's motivation yet again.
