### ISSUE TITLE
Multiple adhesive.dll crashes

### ISSUE THREAD

**Issue by FaultyMatrix** [citizenfx/fivem#2086]
When running our server, the majority of players at random and inconsisent intervals or scenarios, crash due to a adhesive.dll error in the game, without any reason specific to each issue.

**Server Version:** 6543 (Also tried 6445 as well without success)
**Client Verson:** Most are running Beta
**Server Core:** QBCore
 
**Screenshots of errors and their reported scenario**

Joining the server
![uwkz62x](https://github.com/citizenfx/fivem/assets/95166538/c70f2085-b7e0-464d-ae76-abd841c6bcb2)

Leaving Alta Street
![GKBsEzq](https://github.com/citizenfx/fivem/assets/95166538/246ebc5e-c274-4126-8d28-3a245978854c)

Joining the server
![V5tUO2C](https://github.com/citizenfx/fivem/assets/95166538/72b82e0d-1aa1-46c6-8da7-88cc0e389ed2)

Going into a store in Little Seoul
![PTqAJ3O](https://github.com/citizenfx/fivem/assets/95166538/f267fa08-8409-41ed-add3-a62831f205ae)

Joining the server
![0YZNH6R](https://github.com/citizenfx/fivem/assets/95166538/330bba4c-284d-45bb-bd1a-b12a364eb093)

Making a second character
![ENvU1Da](https://github.com/citizenfx/fivem/assets/95166538/216a385a-5221-4f88-950c-206751e0b59e)

Using a clothing menu
![5MdO3HJ](https://github.com/citizenfx/fivem/assets/95166538/e38e90fe-2d84-4c3e-9632-f913397e563c)

Utilising Admin commands to teleport to someone
![KBQF2Oq](https://github.com/citizenfx/fivem/assets/95166538/081abfdb-01b0-4512-8427-f0d50beca9b9)

**Steps to reproduce:**
1. Join the server
2. If you dont crash, go on about your daily business
3. You'll crash at some point

Any other info you need, let me know.

**Comment by LWSS** [comment]
might be a 2612 issue, try running a different version with `sv_enforcegamebuild`

**Comment by FaultyMatrix** [comment]
Currently game build is 2802 weith these issues present, tried 2699 and currently testing.

**Comment by FaultyMatrix** [comment]
Game build revert doesn't seem to have resolved the error, another two crashes in 15 minutes post restart

Crash dumps have been made available as well - see attached most recent dump and crash screenshot:
![Wd04jAv](https://github.com/citizenfx/fivem/assets/95166538/863ba330-5a49-43a3-9a99-200baa67313e)

[CfxCrashDump_2023_07_04_00_25_05.zip](https://github.com/citizenfx/fivem/files/11943212/CfxCrashDump_2023_07_04_00_25_05.zip)

**Comment by Randolio** [comment]
I'm also getting these crashes.

**Comment by reeeum** [comment]
Determined that this DLL issue is something to do with a particular resource.

I took the frame work from our existing server added it to another and still got the same issues.

I have disabled, firewalls, antivirus etc, just to make sure that they weren’t conflicting with the adhesive anti cheat - but this still happens.

Removed the frame work and worked from a fresh install of QBCore and it works perfectly - no crashes.

Using this information I whittled down the current frame work we had to see what resource is causing the DLL issue but due to the amount of resources we had and the lack of information I had on the server dll issue it was hard to pin point the actual cause of the crash.

But I can say with a certainty. It has to be a particular resource. @Randolio if you have a list of your resources, we could do some comparison to see what resource it is?

**Comment by Kairophe** [comment]
I had this issue when reaching 15+ players online, had 2 times this issue, the first one was solved with a fivem client update (had to wait 2-3 days) and the second one in my personal case it was some clothes assets packages made with [Durty Cloth Tool](https://gta.clothing/) probably was my fault on doing the package, my thought was that components (error in crash) in natives refers to clothes, that way found the solution.

Also in some test deactivating Discord Whitelist worked for a while.

Sorry english is not my main language

**Comment by blattersturm** [comment]
This has been fixed by reverting some recent anticheat change.

**Comment by SubwooferNL** [comment]
that adhesive.dll crash has nothing to do with servers......
if i am in the main menu fivem crashes without any reason
