### ISSUE TITLE
DrawLine_2d unexpectedly diagonal

### ISSUE THREAD

**Issue by DemmyDemon** [citizenfx/fivem#2124]
Code to reproduce the problem (on client, obviously):
```lua
local length = 0.05
local center = vector2(0.5, 0.5)

Citizen.CreateThread(function()
    while true do
        -- LINE 1
        DrawLine_2d(
            center.x, center.y-length,
            center.x, center.y+length,
        0.0005, 255, 0, 0, 255)

        -- LINE 2
        DrawLine_2d(
            center.x-length, center.y,
            center.x+length, center.y,
        0.005, 0, 255, 0, 255)

        Citizen.Wait(0)
    end
end)
```
What I expected is that LINE 1 is perfectly vertical, and LINE 2 is perfectly horizontal.
LINE 1 *is* perfectly vertical.
LINE 2 is slightly diagonal.
![image](https://github.com/citizenfx/fivem/assets/734625/fbf31238-29bb-4dc6-868b-1866663f8997)

**Comment by Gogsi** [comment]
Seems that parameter 4 which is documented as `width` is actually used as a rotation (or at least in a similar way as parameter 4 in DRAW_RECT_ROTATED but without converting degrees -> rad)

https://github.com/citizenfx/fivem/blob/8b8d9f631d5881bdf52710decc703fa381e44d77/code/components/extra-natives-five/src/Draw2dNatives.cpp#L65

**Comment by blattersturm** [comment]
I'm rather worried about the `&= 0xFA;` which looks like it should've been ~0xFA perhaps.

**Comment by gottfriedleibniz** [comment]
Took a quick glance at this since it has been sitting for a bit. This seems like an artifact from how the triangle strip is drawn:

```
(x1 - w, y1 - w), (x1 + w, y1 - w), (x2 - w, y2 + w), (x2 + w, y2 + w)
```

As a line becomes more horizontal, the height collapses to `2w` which isn't render-friendly given the vertex ordering.

Looking through that function, I could not find anything that resembles the math for drawing a line `(x1,y1),(x2,y2)` with width `w` as quad (i.e., perpendicular * width) besides this parallelogram approach/approximation. Maybe I'm blind.
