### ISSUE TITLE
SetEntityHealth occasionally fails on build 2802

### ISSUE THREAD

**Issue by MatinHQ** [citizenfx/fivem#2135]
Hello it appears `SetEntityHealth` occasionally breaks on game build 2802

`Error executing native 0x6b76dc1f3ae6e6a3 at address FiveM_b2802_GTAProcess.exe+15EB7A5`

**Comment by thelindat** [comment]
Hijacking this issue since I discussed this with somebody recently; I'll just quote them.

> `SET_ENTITY_HEALTH` actually takes a third argument, [...] I wouldn't be surprised if the OAL bits aren't zeroing out enough (or any) arguments. 

> It'd probably be better to update to codegen script to zero out the next X fields (instead of just memsetting the LuaNativeContext on initialization).

Related: https://github.com/citizenfx/fivem/commit/2e0018bf98d1a56ace9506722b3b5bddd044de3e
I assume this would also resolve https://forum.cfx.re/t/lua-oal-script-loses-entity-ownership-after-using-detachentity/5007847/2?

**Comment by blattersturm** [comment]
Ideally we'd have argument declarations that include newly-added/default parameters, as some native commands get updated to add default parameters that *aren't* 0 (I think there was a -1 or -2 somewhere).

Zeroing out the 'next few' could be a viable workaround for OAL however, indeed.

(Though, I wonder if the issue author actually is using OAL since they're just mentioning 'occasionally' and not providing any other context...)

**Comment by MatinHQ** [comment]
Hello, I am using OAL and I didn't mention because I thought it couldn't be related and for further context there I have no clue how this happens sometimes it just fails for example when I heal player or make the entity health decrease because of hunger and...
