### ISSUE TITLE
 Server list query returned an error: System.Threading.Tasks.TaskCanceledException: A task was canceled. <- System.TimeoutException: A task was canceled. <- System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.

### ISSUE THREAD

**Issue by ChaiyaZ-Dev** [citizenfx/fivem#2172]
```
[ citizen-server-impl] Server list query returned an error: System.Threading.Tasks.TaskCanceledException: A task was canceled. <- System.TimeoutException: A task was canceled. <- System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
[ citizen-server-impl] Server list query returned an error: 
```

![llo](https://github.com/citizenfx/fivem/assets/70051176/ccbb661b-8382-4762-ab9f-737779e06156)

**Comment by blattersturm** [comment]
This is not an actionable client issue. Currently, the server list backend is running at limited capacity so this is a known issue.

(@team: could this perhaps be updated on the [Statuspage instance](https://status.cfx.re/)?)

**Comment by SABogdan** [comment]
Same problem over here. @blattersturm 
But we dont want our server to be listed there as its a private white list one and in the past i think the fix was to have the 
`sv_master1 “”` in the cfg.

Granted i think this appears for us too because the server list backend is running at limited capacity. 


thank you

**Comment by blattersturm** [comment]
There is no way to mark a server as unlisted anymore- the old way to make a server unlisted will merely mark it as private and unable to be connected to.

**Comment by SABogdan** [comment]
> There is no way to mark a server as unlisted anymore- the old way to make a server unlisted will merely mark it as private and unable to be connected to.

Then do we still need sv_master1 "" in the cfg? 

Thank you

**Comment by Vinyljackers** [comment]
Any work arounds so the error is hidden?

**Comment by BadFoxrp** [comment]
**Any update on this problem?**       `[ citizen-server-impl] Server list query returned an error: System.Threading.Tasks.TaskCanceledException: A task was canceled. <- System.TimeoutException: A task was canceled. <- System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.`

**Comment by farastyle** [comment]
bump

**Comment by BetuweBartje** [comment]
Any way to disable the error message or something?
