### ISSUE TITLE
Start building Fivem-master

### ISSUE THREAD

**Issue by hunga516** [citizenfx/fivem#2412]
### What happened?

I start gitclone fivem project from https://github.com/citizenfx/fivem/blob/master/docs/building.md

I have done all require and run cmd.exe as admin (Win11)
```bat
git clone https://github.com/citizenfx/fivem.git -c core.symlinks=true
cd fivem
git submodule update --jobs=16 --init

//I'm using python 3.8.3 so don't rung pip setuptool
fxd get-chrome

:: or -game server/-game rdr3/-game ny
fxd gen -game five
fxd vs -game five
fxd build
```
And when i rebuild solution on VS2019, have more bug:
![image](https://github.com/citizenfx/fivem/assets/53590463/108d28b4-4fcd-4238-a288-e6e27afd4b75)

### Expected result

i dont think

### Reproduction steps

install 
msys64 as C:/msys/64
node and yarn
powershell 7
python 3.8.3

git clone https://github.com/citizenfx/fivem.git -c core.symlinks=true
cd fivem
git submodule update --jobs=16 --init

//I'm using python 3.8.3 so don't rung pip setuptool
fxd get-chrome

:: or -game server/-game rdr3/-game ny
fxd gen -game five
fxd vs -game five
fxd build

### Importancy

Unknown

### Area(s)

FiveM, Natives

### Specific version(s)

fivem rebuild

**Comment by Leoonv2** [comment]
no one is gonna help you there buddy. you should just try yourself or stop trying

**Comment by tens0rfl0w** [comment]
First of all, please don't open two separate issues about the same problem, just because no one "helped" you in your first issue (I tried, but you didn't provide enough info). Also, like already mentioned on your first issue, this is a user error, so the Github repo is not the right place to ask for help (I already told you that in your first issue).

`fxd build` output should give you _more_ info on what went wrong, especially the build task at which building failed.

**Comment by FabianTerhorst** [comment]
Make sure to run the [prebuild.cmd](https://github.com/citizenfx/fivem/blob/master/prebuild.cmd) and [prebuild_natives.cmd](https://github.com/citizenfx/fivem/blob/master/prebuild_natives.cmd) before starting the build.
