### ISSUE TITLE
Setting a state on client is not replicated

### ISSUE THREAD

**Issue by CeebDev** [citizenfx/fivem#2589]
### What happened?

Setting a state on a client with replicated arg to true don't replicate to server and other clients

### Expected result

if replicated arg is set to true it should replicate to server + other clients

### Reproduction steps

- Execute on a client `LocalPlayer.state:set("test", true, true)`
- print server side `print(Player(playerId).state.test)`
- it return nil
- same for other clients

### Importancy

Slight inconvenience

### Area(s)

FiveM, OneSync

### Specific version(s)

Release or Canary client same - b8509 server

**Comment by AvarianKnight** [comment]
Try upgrading to 8510+ the old builds didn't handle state bag packets https://github.com/citizenfx/fivem/commit/d1b50baaf7c273e3c786f030623530058cadb201

**Comment by CeebDev** [comment]
why this fix is not on latest update branch if it's a known bug and a fix is already pushed ?

**Comment by slashkeyvalue** [comment]
It's not a client branch thing, just update your server artifacts

**Comment by CeebDev** [comment]
> It's not a client branch thing, just update your server artifacts

Yes but i mean here https://changelogs-live.fivem.net/api/changelog/versions/linux/server

latest just got updated and the fix was pushed yesterday, so the latest branch was broke for +1day

**Comment by yannbcf** [comment]
Even tho, it does not make sense to replicate a state set by the client, there is a design issue here

**Comment by yannbcf** [comment]
It looks like an attempt to disguise a design issue behind a need to be fair.

What you ask for is a mechanism to reject a behavior that should not happen in the first place, the server developers should have the control over what is synchronized by their gamemodes, and this by design.

I dont see the issue behind sending a classic event to the server, which verifies if it's legit and then, it is the server responsibility to synchronize the state. This way you dont have undefined behaviors if you dont handle the rejection or whatever
