### ISSUE TITLE
Natives Abuse Related To Vehicles

### ISSUE THREAD

**Issue by chozr7** [citizenfx/fivem#2621]
### What happened?

**Their are cheaters currently executing code similar to below**

```lua
local vehicles = GetGamePool('CVehicle')
local players = GetActivePlayers()

for i = 1, #players do
    local playerId = players[i]

    if playerId ~= PlayerId() then
        local playerPed = GetPlayerPed(playerId)
        local playerCoords = GetEntityCoords(playerPed)
        local distance = #(GetEntityCoords(PlayerPedId()) - playerCoords)

        if distance < 20.0 then
            for j = 1, #vehicles do
                local vehicle = vehicles[j]
                
                if NetworkGetEntityOwner(vehicle) == PlayerId() then
                    NetworkSetEntityInvisibleToNetwork(vehicle, true)
                    SetEntityVisible(vehicle, false, true)
               
                    CreateThread(function ()
                        while true do
                            Wait(1000)
                            local coords = GetEntityCoords(GetPlayerPed(playerId))
                            SetEntityCoords(vehicle, coords.x, coords.y, coords.z + 4.0, false, false, false, true)
                            ApplyForceToEntity(vehicle,3,0.0,0.0,-100.0,0.0,0.0,0.0,0,0,1,1,0,1)
                        end
                    end)
                end
            end

            break
        end
    end
end
```

**although they need control/owner of the vehicle, they simply get in and out of any car and they can start smushing a innocent person with a vehicle, they can mess around with what the vehicle does they can make it continuously follow them right behind and hit them from the side and all that.**

### Expected result

I don't even know what to say here... I guess dont let them applyforce or something.

### Reproduction steps

1. Load up into any server
2. Go to an area populated with people
3. Get in a car and get out
3. Run the provided snippet above
4. You will be start seeing the nearest person to you get obliterated.

### Importancy

Slight inconvenience

### Area(s)

FiveM, OneSync, Natives, ScRT: Lua

### Specific version(s)

FiveM Artifacts 8633, Server Game Build 2699, windows

**Comment by AvarianKnight** [comment]
There is no way to fix this, the client controls the vehicles movement velocity, so the client says where it goes.

Even if you were to just no-op the `ApplyForceToEntity` native it would not do anything to stop smarter cheaters from just directly writing to the Velocity data nodes and *still* doing this.

**Comment by chozr7** [comment]
this is scary, I have witnessed my innocent players get smushed and thrown 🥺(i dont know what else to say)

> There is no way to fix this, the client controls the vehicles movement velocity, so the client says where it goes.
> 
> Even if you were to just no-op the `ApplyForceToEntity` native (which is bad for many other compatibility reasons), it would not do anything to stop smarter cheaters from just directly writing to the Velocity data nodes and _still_ doing this.

**Comment by kerneljay** [comment]
Can we not think of an alternative here? Why not have an event handler for it a bit like we do for "explosionEvent", maybe have "forceEvent".

**Comment by AvarianKnight** [comment]
> Can we not think of an alternative here? Why not have an event handler for it a bit like we do for "explosionEvent", maybe have "forceEvent".

Because that's not how it works. Explosion events have to go through the server to be networked to other clients, there isn't anything special for applying force to an entity, it's all done through the physics engine and the velocity is given to the sync trees, so there isn't any event to intercept.

It's all applied directly to sync nodes.

**Comment by kerneljay** [comment]
"there isn't anything special for applying force to an entity" first question why is this? I assume it's engine based, so like literally nothing we can do. But didn't R* not think like oh this is going to definitely get exploited, people are gunna throw shit around and we need to handle this before we release the game. I understand the time of game development was different back then but it really is an issue, I understand exploits and stuff occur in literally every game but as a server owner and someone trying to release a server, it's getting to a point where it's like - wtf is this engine doing?! So... the physics engine applies force client side, we know it does get networked to every client right? So... why is there not a way to intercept the force native. Literally 0 way from my understanding.

**Comment by AvarianKnight** [comment]
> "there isn't anything special for applying force to an entity" first question why is this?

Because you're just modifying the velocity of the entity, physics is all done client side, its not feasible to have this on the server (nor really possible with how FXServer/FiveM are setup currently)

The way this is mainly handled is you can only do things to vehicles you own (for the most part)


> So... the physics engine applies force client side, we know it does get networked to every client right? So... why is there not a way to intercept the force native. Literally 0 way from my understanding.

All of this is done on the client, every single vehicle has its physics done on the client, the only thing the server sends to other clients is the entity's velocity


See: https://github.com/citizenfx/fivem/blob/c132d623ec9d1c5ac6fd150a08ea33616dbd2b19/code/components/citizen-server-impl/include/state/SyncTrees_Five.h#L1540-L1569

You can't hook into this because *everything* sends velocity data, and they get send constantly, for every vehicle, or object on the map (notably not player peds, its velocity is completely calculated on the client), the performance overhead is just too high to intercept this, though you can again already do this on the server if you want, the velocity is already given to the server, see [here](https://natives.avarian.dev/?native=0xC14C9B6B&game=gta5)
