### ISSUE TITLE
Cheaters keep using DevTools in order to make their lives easier. sv_enableDevtools 0 convar.

### ISSUE THREAD

**Issue by d22tny** [citizenfx/fivem#2667]
### What happened?

95% of cheaters use DevTools in order to cheat on a server ( in order to reverse engineer code to understand the workflow of events )

So, why does a client in a production server need DevTools? They don't.

For example, at this moment if i have all my code encrypted using escrow and i have a client code saying :

TriggerServerEvent("givemoney", 10000), the cheater can see via netEventLog that the givemoney with the parameter 10000 was sent from client to server, so, he can use then a lua executor to trigger the same event.

Can you please make a server convar sv_enableDevtools so that we can put that on 0 and maybe enable it only when we have to test something? Also note that this convar should stop all the functioning, at least for the netEventLog devTool, because some cheats are accesing directly the data.

### Expected result

convar to be able to stop devtools functionality

### Reproduction steps

- 

### Importancy

Slight inconvenience

### Area(s)

FiveM

### Specific version(s)

any build

**Comment by matehun00** [comment]
You should never trust what the client says, secure your events. And if you are so scared about DevTools, there are ways to detect it being used

**Comment by ook3D** [comment]
its a good practice to do that, but it shouldnt rely on it, you should in my opinion be able to disable all development features as suggested.

**Comment by AvarianKnight** [comment]
If people are using cheats "blocking" this from being used won't fix anything, they can just bypass it. If you want protect your server, the best way is to validate *anything* that comes from the client.

**Comment by d22tny** [comment]
It's all about coding in a much safer enviroment, coding for fun, not having to think every bit of code 10% for functionality and 90% for security. Obfuscating code is not a viable solution, you write the code and if you go back at it after a month or two you have no idea what is what. And as i've said, @AvarianKnight it should be a convar disabling the entire devtools from working, i'm not aware of any bypass for changing a server convar. 

@ook3D how can i detect netEventLog or its data being used ? have a snippet or something ?

**Comment by thelindat** [comment]
> cheaters use DevTools … in order to reverse engineer code

What lmao?

> i have a client code saying :
>
> TriggerServerEvent("givemoney", 10000)

So don't be lazy and write terrible code.

> at least for the netEventLog devTool, because some cheats are accesing directly the data

Wait until you find out they could access that data in completely different ways or bypass your dumb convar because _client side security is not secure_.

> It's all about … not having to think every bit of code 10% for functionality and 90% for security

Sounds like _you_ need to stop coding.


This post is literally the biggest skill issue I've seen.

**Comment by d22tny** [comment]
Man, you literally have no idea what you're talking about. This attitude is not necessary at all. I didn't share how i write code. They have 2 ways of accesing that data and they are both stoppable.

**Comment by ChatDisabled** [comment]
You got a handful of the top class developers commenting on this issue and you dare say `you literally have no idea what you're talking about` 💀

**Comment by d22tny** [comment]
I wasn't speaking to the handful of the top class developers, i was speaking to this guy @thelindat

**Comment by DemmyDemon** [comment]
> Man, you literally have no idea what you're talking about.

Right, but you trusting the client because you think it might possibly be respecting a convar, that's great security?
Please, it's an annoyance for people *at best*.  Convars are not magic, they're just text strings sent to the client. The client isn't bound by the ancient magic of Baal to respect it, it can just discard it.

This does nothing.

**Comment by d22tny** [comment]
Yup right, i'm a little bit tired, a server command, anything without client access. There are multiple ways of ensuring cheaters can't use cheats.

**Comment by AdrianIsBored** [comment]
> There are multiple ways of ensuring cheaters can't use cheats.
Correct! Disabling devtools isn't one of them, not being able to identify what events are triggered is just a little inconvenience, there is millions of other ways.

**Comment by draobrehtom** [comment]
I believe that hiding devtools and eventlog might partially help in reducing cheaters, as it will make it harder for ordinal cheat users to use current cheats. However, in future new cheats will eventually emerge and ordinal cheat users will be back on track.

**Comment by DemmyDemon** [comment]
Yes, it'll take them 5 minutes to circumvent, this causing it to only be an inconvenience for legitimate users.

The solution is to not have blatantly exploitable events.

**Comment by racistnoob** [comment]
DevTools on its own isn't an issue; the real problem lies in resources that have NUI callbacks which are vulnerable and can be exploited to trigger events without having to use a "lua executor cheat"

Here's an example from [qb-phone](https://github.com/qbcore-framework/qb-phone/blob/main/client%2Fmain.lua#L555-L561)

```lua
RegisterNUICallback('AcceptMailButton', function(data, cb)
    if data.buttonEvent ~= nil or data.buttonData ~= nil then
        TriggerEvent(data.buttonEvent, data.buttonData)
    end
    TriggerServerEvent('qb-phone:server:ClearButtonData', data.mailId)
    cb('ok')
end)

**Comment by AdrianIsBored** [comment]
> the real problem lies in resources that have NUI callbacks which are vulnerable

Cheat or not, vulnerabilities are vulnerabilities, and they will be exploited at some point by an actual malicious actor. Putting a bandage on it only makes it more likely that when someone *capable* is doing some sketchy stuff then it will cause more fuckery since you weren't able to catch them early.

If NUI is the main attack vector for your cheaters, then I must only imagine what other vulnerabilities exist outside of that scope.

**Comment by coblyox** [comment]
> DevTools on its own isn't an issue; the real problem lies in resources that have NUI callbacks which are vulnerable and can be exploited to trigger events without having to use a "lua executor cheat"

And once again, it's laziness or simple incompetence of a developer who wrote it. IMHO, if people don't know what the f they're doing, they should hire a professional or don't touch this thing at all. Because blocking devtools or eventlog won't fix anything as said in this issue before. One way or another, they will get that data and use it against you if it's not secured.

In general, devtools are pretty much same shit as you clicking Right Click -> Inspect in any website, no one sees an issue there, but sees them here.

**Comment by AvarianKnight** [comment]
This is also not to mention that the client has the source code for anything on the client anyways, they can *already* see what everything does.

They already intercept C->S traffic, they already check what data is being sent via events, this is why people preach *put as little on the client that you can*, and if you have to take anything from the client make sure to *verify* it.

> And as i've said, @AvarianKnight it should be a convar disabling the entire devtools from working, i'm not aware of any bypass for changing a server convar.

That isn't how the world works, you can't just magically disable it and the cheaters can't use it, the cheater can do whatever it wants regardless of what you do. 

> It's all about coding in a much safer enviroment, coding for fun, not having to think every bit of code 10% for functionality and 90% for security.

I'm sorry to say but if you're interacting with client -> server events then *this is something you need to think about* you can't just wish this away with a "safer environment", you ***need*** to think about this stuff when you're interacting with data from the client.

**Comment by d22tny** [comment]
I see that this escalated, i meant no harm at all and maybe one day i'll do some forum topic teaching you guys some security. Have a nice day.
