### ISSUE TITLE
TxdStore is not enough. -solved

### ISSUE THREAD

**Issue by HuseyinCecen** [citizenfx/fivem#2807]
### What happened?

Hello, As you know, FiveM servers have more players than ever before. New DLCs are with us now. With the excess of players and DLC, there are many add-on vehicles, clothes, etc. products or items around. The current TxDStore is no longer sufficient. If you deem it appropriate, I request that it be increased.

Thank you in advance for your interest and I wish you good work.

### Expected result

TxdStore limit increase

### Reproduction steps

Before asking for the TxDStore to be increased

Analyze all ytds on your server and apply fixes and mitigations. 
Try optimizing products with high polygon and pixel counts.
If you are experiencing Txdstore crashes, texture distortions, rgb coloring despite these actions. You can support me.

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM 9902 | DLC 3258

### Additional information

I hope you will accept this request to solve the problems of collapse and deterioration.

**Comment by ook3D** [comment]
you can manually adjust the pool size now.

**Comment by HuseyinCecen** [comment]
> you can manually adjust the pool size now.

FiveM does not allow changes via gameconfig. Also, doing so can create imbalance. It is healthier for a specialist to regulate this permanently.

**Comment by d22tny** [comment]
he's not speaking about gameconfig.
increase_pool_size "TxdStore" 26000
26000 is the max limit atm
you can read more here https://github.com/citizenfx/fivem-docs/pull/481/files

**Comment by HuseyinCecen** [comment]
> he's not talking about gameconfig. increase_pool_size "TxdStore" 26000 26000 is the max limit atm you can read more here https://github.com/citizenfx/fivem-docs/pull/481/files

Oh, I'm so sorry. I didn't know such a thing existed. I'll look into it and get right back to you.

**Comment by HuseyinCecen** [comment]
> you can manually adjust the pool size now.

> he's not talking about gameconfig. increase_pool_size "TxdStore" 26000 26000 is the max limit atm you can read more here https://github.com/citizenfx/fivem-docs/pull/481/files

Thank you, this information is useful. But I realized that TxdStore is not the only problem, my problem is the total number of players that can be in a single field. As far as I know, FiveM allows a maximum of 128 players in a given area. Is there any way to increase this?

**Comment by d22tny** [comment]
That is also a much bigger problem on RedM than on FiveM, but yes, at this moment it's capped at 128, that's because players are stored into a array and that's its size 32 for RedM and 128 for FiveM.

Yeah, on my server too when it's a heist or something big i encounter the 128 limit problem as well.

But i don't know how easy is it to modify the array's size and with what side problems it may come.

Idk, maybe you should close this issue as solved and maybe open a new issue for limits.
In my opinion it should be tried : 
RedM Players In Scope : 32 -> 128
FiveM Players In Scope : 128 -> 256
FiveM Modkit IDS -> 1024 -> 64k or even 8k, anything higher would be great

**Comment by HuseyinCecen** [comment]
I'm closing this as resolved. Thanks for the help. I will create a new one for the problem we are talking about.
