### ISSUE TITLE
[FiveM - Build 10272] Repetitive crash

### ISSUE THREAD

**Issue by Spirit-RP** [citizenfx/fivem#2882]
### What happened?

Server crash on fxServer 10272 at Legion Square.
Last DLC GTA.
Server with an average of 150 players in the evenings, a large part crashes.

![crash](https://github.com/user-attachments/assets/dd7a84ac-0553-4850-910b-7a7c84d7428e)

![crashlog](https://github.com/user-attachments/assets/576aeaf1-718b-4635-8744-ce7550e24b15)

Since today (no changes added on our hands).

### Expected result

Normal server operation

### Reproduction steps

1) Open the server.
2) Go to Legion Square.
3) Wait for crash after few seconds.

### Importancy

Crash

### Area(s)

FiveM, FXServer

### Specific version(s)

FiveM 10272

### Additional information

N/A

**Comment by Benaz-sp** [comment]
After several manipulations it turns out that this product charges the area of ​​Legion Square and the Maze Bank when you arrive too quickly near it, this was observed on artifact 10272. 

**Fix:** 
After a passage on artifact 10488 the crashes completely stopped. 

Have a nice day to you beautiful community :)

**Comment by Spirit-RP** [comment]
> After several manipulations it turns out that this product charges the area of ​​Legion Square and the Maze Bank when you arrive too quickly near it, this was observed on artifact 10272.
> 
> **Fix:** After a passage on artifact 10488 the crashes completely stopped.
> 
> Have a nice day to you beautiful community :)

I can confirm that.
