### ISSUE TITLE
[RedM] Issue with AZERTY Keyboard

### ISSUE THREAD

**Issue by Identity-labs** [citizenfx/fivem#2936]
### What happened?

When you have an AZERTY Keyboard you have to rebind all AZQW Keys
When keys are rebinds when you use A key then Q is displayed in prompt, same for Q you see A, and for Z-W, W-Z

Fivem have this issue back in 2017

### Expected result

Handling AZERTY Keyboard correctly without any rebind like base game

### Reproduction steps

Just having AZERTY Keyboard, you can switch language in windows settings to have it

### Importancy

There's a workaround

### Area(s)

RedM

### Specific version(s)

RedM all builds

**Comment by dalekenium-cfx** [comment]
This happens because RedM doesn't force the keyboard into International mode (https://github.com/citizenfx/fivem/blob/91bd18e26c425d8316e98f0f7abbc7630b54e092/code/components/rage-input-rdr3/src/InputHook.cpp#L419) like FiveM does (https://github.com/citizenfx/fivem/blob/91bd18e26c425d8316e98f0f7abbc7630b54e092/code/components/rage-input-five/src/InputHook.cpp#L759).

A fix for this is pending and should be merged soon.

**Comment by Identity-labs** [comment]
Resolved with https://github.com/citizenfx/fivem/commit/7cf4b64e390c0e6c398dae2c53adc156995fa1c8
