### ISSUE TITLE
Inconsistent Update Channel names and versions

### ISSUE THREAD

**Issue by PulseHarbor** [citizenfx/fivem#2964]
### What happened?

When changing the Update Channel, either the wording is confusing, or the build is wrong.
Release - Ver. 11344
Beta - Ver. 11532/beta
Latest (Unstable) - 11516/canary

### Expected result

Latest/Unstable build is on a later build than beta, and or canary name is removed as suggests the build is earlier than beta

### Reproduction steps

1. Settings
2. Game
3. Update Channel

### Importancy

Slight inconvenience

### Area(s)

FiveM

### Specific version(s)

Update Channel

**Comment by tens0rfl0w** [comment]
The build number is an incremented identifier for each CI run and doesn’t necessarily reflect the recency of the code. Beta builds may have higher build numbers because commits are often cherry-picked for Beta and Release builds instead of just using a previous (Canary) build that was deemed stable, while Canary builds track the latest HEAD. So build numbers are primarily used to track issues, not to indicate version "freshness".

**Comment by tens0rfl0w** [comment]
But wouldn't you expect "Latest" to reflect the most recent code, while "Beta" represents a version that only includes commits that have passed an initial stability check? It seems there's some confusion between the actual build time and the HEAD the build is based on. Your proposed change would cause a lot of confusion.

**Comment by CeebDev** [comment]
Seems logic to me, 

Release -> Beta -> Unstable

So if you follow a commit, it will go from right to left.
"Latest" mean the if a new commit is pushed, it will go first in Unstable / Beta
