### ISSUE TITLE
Mouse not responding after tabbing back sometimes

### ISSUE THREAD

**Issue by BoxxiDev** [citizenfx/fivem#40]
After the most recent patch, both me and a number of others have had issues moving the mouse after tabbing out and then in. Does not happen all the time, but rather often.

**Comment by mevans91** [comment]
Having a similar issue with tabbing out of the game window after the latest patch.

Whether in-game or in the menus, while tabbing out and then back into the game it shows only a black screen. Tabbing back out and back in again will then show a frozen screen.
All audio output, and keyboard/mouse input still work.

Happens every time the game is tabbed out, whether this is due to an external application taking focus or from the user pressing alt+tab.

**Comment by rudzboy** [comment]
+1

**Comment by blattersturm** [comment]
@rudzboy -100 we win

**Comment by blattersturm** [comment]
@rudzboy anyhow this issue _is_ being worked on and a fix should be deployed soon :five:

**Comment by BoxxiDev** [comment]
This particular issue is pretty much resolved.
