### ISSUE TITLE
CEF freeze because of <input type="file">

### ISSUE THREAD

**Issue by SnaiCrys** [citizenfx/fivem#986]
We found a problem with the <input type="file"> tag in the CEF.

To reproduce this, you just need to insert this code
`<div style="position: absolute; top: 150px; right: 150px;"><input name="myFile" type="file"></div>`

through nuidevtools or any ui resource, minimize the game for a while (I recommend clicking on other "windows" at this time), then expand the game and try to click on the button in this input. As a result, the entire CEF freezes until the restart. Sometimes you need to try several times to reproduce this. It is not even necessary to go to any server, you can do it in the main menu of the FiveM

**Comment by blattersturm** [comment]
... then don't add a file input?

**Comment by blattersturm** [comment]
Care to provide any more meaningful reply than a "😕" emoji response?

File inputs are not supported as
1. the OS file browser window is not meant for use in a game loop that may be fullscreened.
2. servers have no business accessing user files.

This is not an issue we'll bother fixing as
1. nobody should be using a file input
2. the risk of regressions unrelated to the issue is _way too high_, as it's another issue related to fullscreened games
3. your repro steps sound typical for fullscreen cases, but are also vague and not really reproducible

If at all, we'll rather _remove support for file inputs entirely_, but that's also not a desired outcome as apparently some people _do_ rely on this, so the only viable outcome is not making any change at all.

**Comment by SnaiCrys** [comment]
FiveM actually have a wonderful native file input `window.invokeNative('openFileDialog', key);`, if it returns blob in the future it would solve the problem.

For now, then we'll move on to using links instead of file input. Thanks for the detailed answer.

**Comment by blattersturm** [comment]
What `openFileDialog`? This is not even meant to work in user resources. The fuck?

**Comment by SnaiCrys** [comment]
I'm talking about the fact that it exists on the menu

**Comment by blattersturm** [comment]
What is your use case for accessing user files, anyway?

**Comment by SnaiCrys** [comment]
We have a phone with a messenger where you can send pictures, Instalife, and a police / medical computer. All these features only need pictures.
